"""PROVENANCE.md entries, machine-produced in the established shape.

The format is `web/src/assets/ambience/PROVENANCE.md`'s, which declared
itself the tarot deck's rule: Source with how it was found, Licence with the
date it was confirmed, Transformations specific enough to re-derive the
asset, and a closing paragraph saying why the thing is committed rather than
hotlinked. What this module adds is that the licence line now comes from the
gate's `LicenceConfirmation` — the sentence "confirmed at fetch time" is
produced by the code that did the confirming, not remembered by whoever
wrote the doc.

Two rules, both refusals-by-shape rather than by prompt:

- **The prose is never invented.** `why_committed` is rendered verbatim from
  the recipe, where the schema already refused its absence. Nothing here has
  a default sentence to fall back on.
- **Only this recipe's section is touched.** The entry lives between
  `<!-- animist:begin <slug> -->` / `<!-- animist:end <slug> -->` markers;
  everything outside them — the hand-written licence arguments, the tarot
  file's famous-trap section — is somebody's reasoning, and this module
  reads it only to find where its own block ends.
"""

from __future__ import annotations

from pathlib import Path

from animist.recipe import Recipe
from animist.sources import Confirmed

FILENAME = "PROVENANCE.md"


def _source_lines(recipe: Recipe, source_id: str,
                  confirmed: Confirmed) -> list[str]:
    source = recipe.sources[source_id]
    provider = {"openverse": "the Openverse record API",
                "wikimedia": "the Wikimedia Commons API",
                "wikimedia-category": "the Wikimedia Commons API, per file",
                "procedural": "nobody -- generated by this pipeline, "
                              "no upstream to ask",
                }.get(source.provider, source.provider)
    title = f'"{source.title}"' if source.title else f"`{source_id}`"
    where = f", <{source.landing}>" if source.landing else ""
    found = f", found via {source.found_via}" if source.found_via else ""
    seeded = (f" Procedural, seed {source.seed}."
              if source.provider == "procedural" else "")
    lines = [f"- **Source**: {title}{where}{found}.{seeded}"]
    proof = confirmed.confirmation
    lines.append(
        f"- **Licence**: {proof.licence}. Confirmed through {provider} at "
        f"fetch time ({proof.checked_on}).")
    if confirmed.skipped:
        skipped = ", ".join(f"`{name}`" for name in confirmed.skipped)
        lines.append(
            f"- **Skipped by the filename guard** "
            f"(`{source.require_filename_prefix}`): {skipped}. Reported "
            "rather than silent, so a re-fetch that skips a different set "
            "is visible.")
    return lines


def _op_line(name: str, params: dict[str, object]) -> str:
    if not params:
        return f"  - `{name}`."
    rendered = ", ".join(f"{key}={value!r}" for key, value in params.items())
    return f"  - `{name}`: {rendered}."


def render(recipe: Recipe, confirmations: dict[str, Confirmed],
           produced: dict[str, list[str]]) -> str:
    """The entry for one recipe. `produced` maps source id -> file names."""
    files = sorted({name for names in produced.values() for name in names})
    lines = [f"## {', '.join(files)}", ""]
    for source_id in sorted(produced):
        if len(produced) > 1:
            lines.append(f"### from `{source_id}`")
        lines.extend(_source_lines(recipe, source_id,
                                   confirmations[source_id]))
        lines.append("- **Transformations** (Pillow, scripted -- "
                     f"`animist build {recipe.path.name}`):")
        for output in recipe.outputs:
            if output.source != source_id:
                continue
            for op in output.ops:
                lines.append(_op_line(op.name, op.params))
            if output.encode.crf is not None:
                lines.append(f"  - Encoded {output.encode.format.upper()}, "
                             f"crf {output.encode.crf}.")
            else:
                lines.append(f"  - Encoded {output.encode.format.upper()}, "
                             f"quality {output.encode.quality}.")
        lines.append("")
    lines.append(f"Why committed rather than hotlinked: {recipe.why_committed}")
    return "\n".join(lines).rstrip() + "\n"


def update(recipe: Recipe, entry: str) -> Path:
    """Write the entry into the recipe directory's PROVENANCE.md.

    Idempotent: the block between this recipe's markers is replaced when it
    exists and appended when it does not, and nothing outside the markers is
    rewritten. A directory without a PROVENANCE.md gets one with the
    standard opening line.
    """
    path = recipe.directory / FILENAME
    begin = f"<!-- animist:begin {recipe.slug} -->"
    end = f"<!-- animist:end {recipe.slug} -->"
    block = f"{begin}\n{entry}{end}\n"

    if path.exists():
        text = path.read_text(encoding="utf-8")
    else:
        text = (f"# {recipe.directory.name} assets -- provenance\n\n"
                "The rule here is the tarot deck's "
                "(`assets/tarot/PROVENANCE.md`): nothing ships in "
                "this directory whose licence was not checked per file, and "
                "every transformation applied is written down so the "
                "derivation is reproducible from the source.\n\n")

    if begin in text and end in text:
        head, rest = text.split(begin, 1)
        _, tail = rest.split(end, 1)
        text = head + block + tail.lstrip("\n")
    else:
        text = text.rstrip("\n") + "\n\n" + block
    path.write_text(text, encoding="utf-8")
    return path
