"""A small DuckDB pool, for the tests that cannot run without one.

Most of this project's tests deliberately need no database -- the mana solver,
the gate and the simulator all take plain records, which is what keeps them
fast and what ADR 2 was protecting. Two things are the exception, and they are
the reason this file grew:

* **Import** refuses to run without the pool, because that is *the* rule it
  enforces (rule 1, never evaluate a card from memory), so testing it against
  a fake would test the wrong thing.
* **The API's card-fact endpoints** -- swap, add, suggestions, card search --
  look every name up. Until this fixture existed they were gated on the real
  `data/mtg.duckdb`, which meant they ran on the maintainer's laptop and
  skipped in CI: 29 tests and five points of coverage that no pull request
  ever exercised.

**Every value here was read out of the real pool, never typed from memory.**
Rule 1 applies to test data too -- a fixture that names a real card and then
lies about it teaches the wrong thing, and would hide exactly the class of bug
this project has already been bitten by twice. The rows were generated by
querying `oracle_cards` and are pasted verbatim, with two deliberate trims.
`legalities` carries only the `commander` key, because that is the only one any
code path reads (`json_extract_string(legalities, 'commander')` in `db.search`,
and `CardRecord.legal_commander`). Carrying the other twenty formats would
quadruple the file to say nothing. And `PRINTINGS` carries each printing's
`artist` but not its `flavor_text`: the painter is what `pool_is_stale` asks
about, so a fixture without one reports itself as an old pool, while the
flavour text is prose nothing here reads.

**This is not a card pool redistribution.** Twenty-one cards chosen to exercise
resolution rules is a test fixture; ADR 6 and rule 5 are about the bulk data,
which stays out of git and off the image. If this file ever needs to grow to
the size where that distinction gets uncomfortable, that is the signal to make
CI build a card pool rather than commit one.

What each card is here for:

* **Gyome, Master Chef** -- a legendary commander, and the B/G identity the
  import tests resolve against.
* **Sol Ring** -- a colourless artifact every deck can legally run.
* **Swamp** / **Forest** -- basics, exempt from the singleton rule, so a
  fixture deck can reach 99 cards without inventing 90 distinct ones.
* **Primeval Titan** -- banned in Commander, so the gate has something real to
  catch on day one.
* **Emrakul, the Aeons Torn** -- also banned, and the second half of the pair
  the pool tools exist for: `search_cards` filters to Commander-legal, so
  both of the cards the real library deliberately fails on were invisible to
  discovery and got answered from recall once already.
* **Ajani, Nacatl Pariah** -- the rule 2 cautionary tale in CLAUDE.md, in the
  fixture so it is executable rather than only written down. White front, red
  back, so a lookup by the front face must still report {R}{W}; derived from
  the mana cost it reads as mono-white and passes a Selesnya legality check it
  should fail.
* **Etali, Primal Conqueror** -- a double-faced card, the one shape where
  Scryfall puts the stats *and the mana cost* on the faces rather than on the
  card. Reading only the top level is how 501 cards ended up in the pool as
  free spells.
* **Smothering Tithe** -- on the official Game Changers list, so a bracket
  count has something real to find.
* **Goreclaw, Terror of Qal Sisma** -- the mono-green commander the synthetic
  deck below is built around.
* **Cultivator Colossus**, **Llanowar Reborn** -- legal mono-green cards to
  swap and add.
* **Rhystic Study** ({U}) and **Swords to Plowshares** ({W}) -- outside a
  mono-green commander's identity, so a refusal has something to refuse.
* **Black Lotus** -- not legal in Commander, which is a different refusal from
  the identity one and must not be conflated with it.
* **Bag End Banquet** -- a colourless artifact at cmc 6.
* **Regal Behemoth**, **Craterhoof Behemoth**, **Terastodon**,
  **Woodfall Primus**, **Vorinclex, Voice of Hunger** -- mono-green creatures
  between cmc 6 and 8. `suggest.candidate_pool` prefilters to legal cards
  inside the identity within +/-2 of the target's cost and of the same primary
  type, so these are what makes a *real* shortlist for Primeval Titan's slot
  rather than an empty list that asserts nothing.
* **Ajani Steadfast Emblem** -- the one thing here that is not a card. It
  shares a first word with the Ajani above, so the camera reader's
  "emblems are not cards" filter has something that can actually rank
  highly when it breaks. See the comment on the row itself.

`PRINTINGS`, further down, is the same idea for the `printings` table: real
rows, chosen for the cases the camera's corner tier has to survive.
"""

from __future__ import annotations

import json
import shutil
import tempfile
from pathlib import Path

CARDS = [
    {'oracle_id': '2588f348-d7a3-46c8-9ace-dca53ed5ef99',
     'name': 'Ajani, Nacatl Pariah // Ajani, Nacatl Avenger',
     'mana_cost': '{1}{W}',
     'cmc': 2.0,
     'type_line': 'Legendary Creature — Cat Warrior // Legendary '
                  'Planeswalker — Ajani',
     'oracle_text': None,
     'colors': [],
     'color_identity': ['R', 'W'],
     'keywords': ['Transform'],
     'produced_mana': [],
     'legalities': {'commander': 'legal'},
     'layout': 'transform',
     'reserved': False,
     'edhrec_rank': 4482,
     'released_at': '2024-06-14',
     'set': 'mh3',
     'card_faces': [{'object': 'card_face',
                     'name': 'Ajani, Nacatl Pariah',
                     'mana_cost': '{1}{W}',
                     'type_line': 'Legendary Creature — Cat Warrior',
                     'oracle_text': 'When Ajani enters, create a 2/1 white '
                                    'Cat Warrior creature token.\n'
                                    'Whenever one or more other Cats you '
                                    'control die, you may exile Ajani, then '
                                    'return him to the battlefield '
                                    "transformed under his owner's control.",
                     'colors': ['W'],
                     'power': '1',
                     'toughness': '2',
                     'flavor_text': 'His pride denied him; his brother did '
                                    'not.',
                     'artist': 'Chris Rallis',
                     'artist_id': 'a8e7b854-b15a-421a-b66d-6e68187ae285',
                     'illustration_id': '3dff950b-68c7-4b2d-a8e5-419b140d897e',
                     'image_uris': {'small': 'https://cards.scryfall.io/small/front/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.jpg?1783911238',
                                    'normal': 'https://cards.scryfall.io/normal/front/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.jpg?1783911238',
                                    'large': 'https://cards.scryfall.io/large/front/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.jpg?1783911238',
                                    'png': 'https://cards.scryfall.io/png/front/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.png?1783911238',
                                    'art_crop': 'https://cards.scryfall.io/art_crop/front/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.jpg?1783911238',
                                    'border_crop': 'https://cards.scryfall.io/border_crop/front/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.jpg?1783911238',
                                    'thumb': 'https://cards.scryfall.io/thumb/front/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.webp?1783911238',
                                    'grid': 'https://cards.scryfall.io/grid/front/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.webp?1783911238',
                                    'display': 'https://cards.scryfall.io/display/front/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.webp?1783911238',
                                    'art': 'https://cards.scryfall.io/art/front/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.webp?1783911238',
                                    'crop': 'https://cards.scryfall.io/crop/front/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.webp?1783911238'}},
                    {'object': 'card_face',
                     'name': 'Ajani, Nacatl Avenger',
                     'mana_cost': '',
                     'type_line': 'Legendary Planeswalker — Ajani',
                     'oracle_text': '+2: Put a +1/+1 counter on each Cat you '
                                    'control.\n'
                                    '0: Create a 2/1 white Cat Warrior '
                                    'creature token. When you do, if you '
                                    'control a red permanent other than '
                                    'Ajani, he deals damage equal to the '
                                    'number of creatures you control to any '
                                    'target.\n'
                                    '−4: Each opponent chooses an artifact, '
                                    'a creature, an enchantment, and a '
                                    'planeswalker from among the nonland '
                                    'permanents they control, then '
                                    'sacrifices the rest.',
                     'colors': ['R', 'W'],
                     'color_indicator': ['R', 'W'],
                     'loyalty': '3',
                     'artist': 'Chris Rallis',
                     'artist_id': 'a8e7b854-b15a-421a-b66d-6e68187ae285',
                     'illustration_id': '941b8c13-e0db-4ef8-8182-17ae977e65a7',
                     'image_uris': {'small': 'https://cards.scryfall.io/small/back/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.jpg?1783911238',
                                    'normal': 'https://cards.scryfall.io/normal/back/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.jpg?1783911238',
                                    'large': 'https://cards.scryfall.io/large/back/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.jpg?1783911238',
                                    'png': 'https://cards.scryfall.io/png/back/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.png?1783911238',
                                    'art_crop': 'https://cards.scryfall.io/art_crop/back/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.jpg?1783911238',
                                    'border_crop': 'https://cards.scryfall.io/border_crop/back/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.jpg?1783911238',
                                    'thumb': 'https://cards.scryfall.io/thumb/back/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.webp?1783911238',
                                    'grid': 'https://cards.scryfall.io/grid/back/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.webp?1783911238',
                                    'display': 'https://cards.scryfall.io/display/back/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.webp?1783911238',
                                    'art': 'https://cards.scryfall.io/art/back/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.webp?1783911238',
                                    'crop': 'https://cards.scryfall.io/crop/back/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.webp?1783911238'}}]},
    {'oracle_id': '900ca697-ad38-4b2b-bc74-2ff7eb6ea951',
     'name': 'Emrakul, the Aeons Torn',
     'mana_cost': '{15}',
     'cmc': 15.0,
     'type_line': 'Legendary Creature — Eldrazi',
     'oracle_text': "This spell can't be countered.\n"
                    'When you cast this spell, take an extra turn after this '
                    'one.\n'
                    'Flying, protection from spells that are one or more '
                    'colors, annihilator 6\n'
                    'When Emrakul is put into a graveyard from anywhere, its '
                    'owner shuffles their graveyard into their library.',
     'colors': [],
     'color_identity': [],
     'keywords': ['Flying', 'Annihilator', 'Protection'],
     'produced_mana': [],
     'legalities': {'commander': 'banned'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': None,
     'released_at': '2022-07-08',
     'set': '2x2',
     'power': '15',
     'toughness': '15',
     'artist': 'Mark Tedin',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/2/4/249db4d4-2542-47ee-a216-e13ffbc2319c.jpg?1783921940',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/2/4/249db4d4-2542-47ee-a216-e13ffbc2319c.jpg?1783921940'}},
    {'oracle_id': '0f1b5cea-2035-444c-9f63-87dcb9782c74',
     'name': 'Gyome, Master Chef',
     'mana_cost': '{2}{B}{G}',
     'cmc': 4.0,
     'type_line': 'Legendary Creature — Troll Warlock',
     'oracle_text': 'Trample\n'
                    'At the beginning of your end step, create a number of '
                    'Food tokens equal to the number of nontoken creatures '
                    'you had enter the battlefield under your control this '
                    'turn.\n'
                    '{1}, Sacrifice a Food: Target creature gains '
                    'indestructible until end of turn. Tap it.',
     'colors': ['B', 'G'],
     'color_identity': ['B', 'G'],
     'keywords': ['Food', 'Trample'],
     'produced_mana': [],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': 4740,
     'released_at': '2026-04-24',
     'set': 'soc',
     'power': '5',
     'toughness': '3',
     'artist': 'Steve Prescott',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/8/2/8279d421-dd86-49d1-93f7-65f6046c542d.jpg?1783903751',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/8/2/8279d421-dd86-49d1-93f7-65f6046c542d.jpg?1783903751'}},
    {'oracle_id': '6ad8011d-3471-4369-9d68-b264cc027487',
     'name': 'Sol Ring',
     'mana_cost': '{1}',
     'cmc': 1.0,
     'type_line': 'Artifact',
     'oracle_text': '{T}: Add {C}{C}.',
     'colors': [],
     'color_identity': [],
     'keywords': [],
     'produced_mana': ['C'],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': 1,
     'released_at': '2026-06-26',
     'set': 'msc',
     'artist': 'Myles Wohl',
     'flavor_text': '"The subject of innovation will always be near and dear '
                    'to my heart."\n'
                    '—Tony Stark',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/9/1/91fdb56b-54d5-4272-8319-505ff987fe9b.jpg?1783903215',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/9/1/91fdb56b-54d5-4272-8319-505ff987fe9b.jpg?1783903215'}},
    {'oracle_id': '56719f6a-1a6c-4c0a-8d21-18f7d7350b68',
     'name': 'Swamp',
     'mana_cost': '',
     'cmc': 0.0,
     'type_line': 'Basic Land — Swamp',
     'oracle_text': '({T}: Add {B}.)',
     'colors': [],
     'color_identity': ['B'],
     'keywords': [],
     'produced_mana': ['B'],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': None,
     'released_at': '2026-11-13',
     'set': 'trk',
     'artist': 'Bastien Grivet',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/b/7/b7387103-1df1-4fd0-9e91-1544509792c7.jpg?1785981659',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/b/7/b7387103-1df1-4fd0-9e91-1544509792c7.jpg?1785981659'}},
    {'oracle_id': 'ae83ef2c-960f-4c5b-97cc-52465c687c18',
     'name': 'Primeval Titan',
     'mana_cost': '{4}{G}{G}',
     'cmc': 6.0,
     'type_line': 'Creature — Giant',
     'oracle_text': 'Trample\n'
                    'Whenever this creature enters or attacks, you may '
                    'search your library for up to two land cards, put them '
                    'onto the battlefield tapped, then shuffle.',
     'colors': ['G'],
     'color_identity': ['G'],
     'keywords': ['Trample'],
     'produced_mana': [],
     'legalities': {'commander': 'banned'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': None,
     'released_at': '2017-11-17',
     'set': 'ima',
     'power': '6',
     'toughness': '6',
     'artist': 'Aleksi Briclot',
     'flavor_text': 'When nature calls, *run*.',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/6/d/6d5537da-112e-4679-a113-b5d7ce32a66b.jpg?1783935516',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/6/d/6d5537da-112e-4679-a113-b5d7ce32a66b.jpg?1783935516'}},
    {'oracle_id': '153376c9-dffd-458c-8ce3-a4c8269bc4e9',
     'name': 'Smothering Tithe',
     'mana_cost': '{3}{W}',
     'cmc': 4.0,
     'type_line': 'Enchantment',
     'oracle_text': 'Whenever an opponent draws a card, that player may pay '
                    "{2}. If the player doesn't, you create a Treasure "
                    'token. (It\'s an artifact with "{T}, Sacrifice this '
                    'token: Add one mana of any color.")',
     'colors': ['W'],
     'color_identity': ['W'],
     'keywords': ['Treasure'],
     'produced_mana': ['B', 'G', 'R', 'U', 'W'],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': 63,
     'released_at': '2023-08-04',
     'set': 'cmm',
     'artist': 'Mark Behm',
     'flavor_text': '"I await your donation."\n—Dasha, Orzhov priest',
     'game_changer': True,
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/8/6/861b5889-0183-4bee-afeb-a4b2aa700a8e.jpg?1783915712',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/8/6/861b5889-0183-4bee-afeb-a4b2aa700a8e.jpg?1783915712'}},
    {'oracle_id': 'befb211f-37ca-4083-98d4-9ff1f28be3f2',
     'name': 'Goreclaw, Terror of Qal Sisma',
     'mana_cost': '{3}{G}',
     'cmc': 4.0,
     'type_line': 'Legendary Creature — Bear',
     'oracle_text': 'Creature spells you cast with power 4 or greater cost '
                    '{2} less to cast.\n'
                    'Whenever Goreclaw attacks, each creature you control '
                    'with power 4 or greater gets +1/+1 and gains trample '
                    'until end of turn.',
     'colors': ['G'],
     'color_identity': ['G'],
     'keywords': [],
     'produced_mana': [],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': 674,
     'released_at': '2023-08-04',
     'set': 'cmm',
     'power': '4',
     'toughness': '3',
     'artist': 'Svetlin Velinov',
     'flavor_text': "You don't want to know how she got that name.",
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/e/e/ee47f23a-3ba9-4615-b170-c89d8ab99d78.jpg?1783915630',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/e/e/ee47f23a-3ba9-4615-b170-c89d8ab99d78.jpg?1783915630'}},
    {'oracle_id': 'b34bb2dc-c1af-4d77-b0b3-a0fb342a5fc6',
     'name': 'Forest',
     'mana_cost': '',
     'cmc': 0.0,
     'type_line': 'Basic Land — Forest',
     'oracle_text': '({T}: Add {G}.)',
     'colors': [],
     'color_identity': ['G'],
     'keywords': [],
     'produced_mana': ['G'],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': None,
     'released_at': '2026-11-13',
     'set': 'trk',
     'artist': 'Bastien Grivet',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/d/c/dce15387-4114-4b3e-91aa-5b42b45c44ac.jpg?1785981675',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/d/c/dce15387-4114-4b3e-91aa-5b42b45c44ac.jpg?1785981675'}},
    {'oracle_id': '92acb789-0e42-465c-ac16-40fefec48805',
     'name': 'Llanowar Reborn',
     'mana_cost': '',
     'cmc': 0.0,
     'type_line': 'Land',
     'oracle_text': 'This land enters tapped.\n'
                    '{T}: Add {G}.\n'
                    'Graft 1 (This land enters with a +1/+1 counter on it. '
                    'Whenever a creature enters, you may move a +1/+1 '
                    'counter from this land onto it.)',
     'colors': [],
     'color_identity': ['G'],
     'keywords': ['Graft'],
     'produced_mana': ['G'],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': 2328,
     'released_at': '2023-11-17',
     'set': 'lcc',
     'artist': 'Philip Straub',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/2/8/284e165e-9ab6-47fc-9685-0fb03de237df.jpg?1783913826',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/2/8/284e165e-9ab6-47fc-9685-0fb03de237df.jpg?1783913826'}},
    {'oracle_id': '4d8505d3-c8a1-4850-95d4-5ddb8ad49770',
     'name': 'Cultivator Colossus',
     'mana_cost': '{4}{G}{G}{G}',
     'cmc': 7.0,
     'type_line': 'Creature — Plant Beast',
     'oracle_text': 'Trample\n'
                    "Cultivator Colossus's power and toughness are each "
                    'equal to the number of lands you control.\n'
                    'When this creature enters, you may put a land card from '
                    'your hand onto the battlefield tapped. If you do, draw '
                    'a card and repeat this process.',
     'colors': ['G'],
     'color_identity': ['G'],
     'keywords': ['Trample'],
     'produced_mana': [],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': 1589,
     'released_at': '2025-01-24',
     'set': 'inr',
     'power': '*',
     'toughness': '*',
     'artist': 'Antonio José Manzanedo',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/4/2/426ed66e-41b3-4e44-90a2-697aafaa8c5c.jpg?1783908104',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/4/2/426ed66e-41b3-4e44-90a2-697aafaa8c5c.jpg?1783908104'}},
    {'oracle_id': '53236dd7-845a-444c-96d5-f41ed7325d8f',
     'name': 'Rhystic Study',
     'mana_cost': '{2}{U}',
     'cmc': 3.0,
     'type_line': 'Enchantment',
     'oracle_text': 'Whenever an opponent casts a spell, you may draw a card '
                    'unless that player pays {1}.',
     'colors': ['U'],
     'color_identity': ['U'],
     'keywords': [],
     'produced_mana': [],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': 44,
     'released_at': '2022-12-02',
     'set': 'j22',
     'artist': 'Tatiana Kirgetova',
     'flavor_text': '"I\'ll teach you the leyline paratrigonometrics, no '
                    'problem. But you need to show me how to make that fiery '
                    'swirly thing."\n'
                    '—Zimone, to Rootha',
     'game_changer': True,
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/9/f/9f37c5b6-a59c-45cd-9a99-e9357fe9ea1b.jpg?1783919146',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/9/f/9f37c5b6-a59c-45cd-9a99-e9357fe9ea1b.jpg?1783919146'}},
    {'oracle_id': 'b1544f21-7e98-461b-aed5-e748b0168c52',
     'name': 'Swords to Plowshares',
     'mana_cost': '{W}',
     'cmc': 1.0,
     'type_line': 'Instant',
     'oracle_text': 'Exile target creature. Its controller gains life equal '
                    'to its power.',
     'colors': ['W'],
     'color_identity': ['W'],
     'keywords': [],
     'produced_mana': [],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': 11,
     'released_at': '2026-06-26',
     'set': 'msc',
     'artist': 'Greg Smallwood',
     'flavor_text': '"Gotta get that corn planted before the world ends '
                    'again."\n'
                    '—Clint Barton',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/b/4/b4e9c870-23c0-413a-ae39-265f09da16d1.jpg?1783903243',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/b/4/b4e9c870-23c0-413a-ae39-265f09da16d1.jpg?1783903243'}},
    {'oracle_id': '5089ec1a-f881-4d55-af14-5d996171203b',
     'name': 'Black Lotus',
     'mana_cost': '{0}',
     'cmc': 0.0,
     'type_line': 'Artifact',
     'oracle_text': '{T}, Sacrifice this artifact: Add three mana of any one '
                    'color.',
     'colors': [],
     'color_identity': [],
     'keywords': [],
     'produced_mana': ['B', 'G', 'R', 'U', 'W'],
     'legalities': {'commander': 'banned'},
     'layout': 'normal',
     'reserved': True,
     'edhrec_rank': None,
     'released_at': '2014-06-16',
     'set': 'vma',
     'artist': 'Chris Rahn',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/b/d/bd8fa327-dd41-4737-8f19-2cf5eb1f7cdd.jpg?1783939332',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/b/d/bd8fa327-dd41-4737-8f19-2cf5eb1f7cdd.jpg?1783939332'}},
    {'oracle_id': '2522a9dd-bcf3-4b84-abff-52b9e6dbde34',
     'name': 'Bag End Banquet',
     'mana_cost': '{6}',
     'cmc': 6.0,
     'type_line': 'Artifact',
     'oracle_text': 'When this artifact enters, create three Food tokens.\n'
                    '{T}: Add {C} for each Food you control.',
     'colors': [],
     'color_identity': [],
     'keywords': ['Food'],
     'produced_mana': ['C'],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': 21221,
     'released_at': '2026-08-14',
     'set': 'hoc',
     'artist': 'Dmitry Burmak',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/0/2/028f284b-4b4c-44e2-8ded-bc59ec71250f.jpg?1784377206',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/0/2/028f284b-4b4c-44e2-8ded-bc59ec71250f.jpg?1784377206'}},
    {'oracle_id': '797c2b1c-c373-4735-b397-f561559c7c61',
     'name': 'Regal Behemoth',
     'mana_cost': '{4}{G}{G}',
     'cmc': 6.0,
     'type_line': 'Creature — Dinosaur',
     'oracle_text': 'Trample\n'
                    'When this creature enters, you become the monarch.\n'
                    "Whenever you tap a land for mana while you're the "
                    'monarch, add an additional one mana of any color.',
     'colors': ['G'],
     'color_identity': ['G'],
     'keywords': ['Trample'],
     'produced_mana': ['B', 'G', 'R', 'U', 'W'],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': 2393,
     'released_at': '2023-11-17',
     'set': 'lcc',
     'power': '5',
     'toughness': '5',
     'artist': 'Jakub Kasper',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/e/3/e3a8bdfa-a39c-4ca7-b591-1c6aca4cc5ac.jpg?1783913856',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/e/3/e3a8bdfa-a39c-4ca7-b591-1c6aca4cc5ac.jpg?1783913856'}},
    {'oracle_id': '8c52bd39-0586-48ca-b263-17210cf9feb6',
     'name': 'Craterhoof Behemoth',
     'mana_cost': '{5}{G}{G}{G}',
     'cmc': 8.0,
     'type_line': 'Creature — Beast',
     'oracle_text': 'Haste\n'
                    'When this creature enters, creatures you control gain '
                    'trample and get +X/+X until end of turn, where X is the '
                    'number of creatures you control.',
     'colors': ['G'],
     'color_identity': ['G'],
     'keywords': ['Haste'],
     'produced_mana': [],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': 315,
     'released_at': '2025-04-11',
     'set': 'tdm',
     'power': '5',
     'toughness': '5',
     'artist': 'Magali Villeneuve',
     'flavor_text': '"Some days, you wish you were fighting a dragon."\n'
                    '—Eshki Dragonclaw',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/2/7/276f5cee-a501-4658-bd4d-7a044bf1ccbc.jpg?1783907345',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/2/7/276f5cee-a501-4658-bd4d-7a044bf1ccbc.jpg?1783907345'}},
    {'oracle_id': '17975a20-2c13-4325-be1e-0bcda5063a2d',
     'name': 'Terastodon',
     'mana_cost': '{6}{G}{G}',
     'cmc': 8.0,
     'type_line': 'Creature — Elephant',
     'oracle_text': 'When this creature enters, you may destroy up to three '
                    'target noncreature permanents. For each permanent put '
                    'into a graveyard this way, its controller creates a 3/3 '
                    'green Elephant creature token.',
     'colors': ['G'],
     'color_identity': ['G'],
     'keywords': [],
     'produced_mana': [],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': 1375,
     'released_at': '2021-04-23',
     'set': 'c21',
     'power': '9',
     'toughness': '9',
     'artist': 'Lars Grant-West',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/6/3/63195796-197e-47ec-85f0-d4ec0065f6e6.jpg?1783927528',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/6/3/63195796-197e-47ec-85f0-d4ec0065f6e6.jpg?1783927528'}},
    {'oracle_id': '2f70f1bb-29fa-4abb-afc2-653acd0a08b9',
     'name': 'Woodfall Primus',
     'mana_cost': '{5}{G}{G}{G}',
     'cmc': 8.0,
     'type_line': 'Creature — Treefolk Shaman',
     'oracle_text': 'Trample\n'
                    'When this creature enters, destroy target noncreature '
                    'permanent.\n'
                    'Persist (When this creature dies, if it had no -1/-1 '
                    'counters on it, return it to the battlefield under its '
                    "owner's control with a -1/-1 counter on it.)",
     'colors': ['G'],
     'color_identity': ['G'],
     'keywords': ['Persist', 'Trample'],
     'produced_mana': [],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': 3942,
     'released_at': '2022-04-29',
     'set': 'ncc',
     'power': '6',
     'toughness': '6',
     'artist': 'Adam Rex',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/9/7/97914abe-71d5-4bd6-87d7-8e7379abf1aa.jpg?1783923235',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/9/7/97914abe-71d5-4bd6-87d7-8e7379abf1aa.jpg?1783923235'}},
    {'oracle_id': 'dbf0ad03-ab31-49d2-89b1-05b45948a61f',
     'name': 'Vorinclex, Voice of Hunger',
     'mana_cost': '{6}{G}{G}',
     'cmc': 8.0,
     'type_line': 'Legendary Creature — Phyrexian Praetor',
     'oracle_text': 'Trample\n'
                    'Whenever you tap a land for mana, add one mana of any '
                    'type that land produced.\n'
                    'Whenever an opponent taps a land for mana, that land '
                    "doesn't untap during its controller's next untap step.",
     'colors': ['G'],
     'color_identity': ['G'],
     'keywords': ['Trample'],
     'produced_mana': ['B', 'G', 'R', 'U', 'W'],
     'legalities': {'commander': 'legal'},
     'layout': 'normal',
     'reserved': False,
     'edhrec_rank': 1790,
     'released_at': '2017-11-17',
     'set': 'ima',
     'power': '7',
     'toughness': '6',
     'artist': 'Karl Kopinski',
     'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/9/f/9fe3af8c-109d-486c-aa34-3f023abda5b7.jpg?1783935514',
                    'art_crop': 'https://cards.scryfall.io/art_crop/front/9/f/9fe3af8c-109d-486c-aa34-3f023abda5b7.jpg?1783935514'}},
    # A double-faced card, shaped exactly as Scryfall serves one: no top-level
    # `mana_cost`, `power` or `toughness`, all of it on the faces. Reading only
    # the top level makes this a free 0/0, which is precisely the bug the
    # front-face fallback fixes.
    #
    # Every value here is copied from the real Scryfall row, including the
    # {G}{R} identity that a mono-green reading of the name would get wrong.
    # A fixture that names a real card and then lies about it is a fixture
    # that teaches the wrong thing -- rule 1 applies to test data too.
    {"oracle_id": "id-etali", "name": "Etali, Primal Conqueror // Etali, Primal "
                                      "Sickness",
     "cmc": 7,
     "type_line": "Legendary Creature — Elder Dinosaur // Legendary Creature "
                  "— Phyrexian Elder Dinosaur",
     "colors": ["R"], "color_identity": ["G", "R"],
     "keywords": ["Indestructible", "Transform", "Trample"],
     "produced_mana": [], "legalities": {"commander": "legal"},
     "layout": "transform", "reserved": False, "edhrec_rank": 790,
     "released_at": "2023-04-21", "set": "one",
     "game_changer": False,
     "card_faces": [
         {"name": "Etali, Primal Conqueror", "mana_cost": "{5}{R}{R}",
          "type_line": "Legendary Creature — Elder Dinosaur",
          "oracle_text": "When this creature enters, each player exiles cards "
                         "from the top of their library.",
          "power": "7", "toughness": "7", "artist": "Ryan Pancoast",
          "image_uris": {"normal": "https://img/etali.jpg",
                         "art_crop": "https://img/etali-art.jpg"}},
         {"name": "Etali, Primal Sickness", "mana_cost": "",
          "type_line": "Legendary Creature — Phyrexian Elder Dinosaur",
          "oracle_text": "Toxic 10. Trample.",
          "power": "11", "toughness": "11", "artist": "Ryan Pancoast",
          "flavor_text": "The contagion spreads and the Multiverse quakes."},
     ]},
    # A non-card, and the only one here. `cards/identify.py` filters on
    # commander legality `IN ('legal', 'banned')`, which is what keeps
    # emblems, schemes, planes and vanguards out of a reading -- none of them
    # can be in a deck, and every one of them is in `oracle_cards`. This one
    # is chosen so that the test can fail: it shares a first word with
    # `Ajani, Nacatl Pariah` above, so a title read as "Ajani" ranks it
    # highly the moment the filter regresses to `= 'legal'`.
    {'oracle_id': '28ca9176-6d8a-41fa-8be5-4b12fc73f1a2',
     'name': 'Ajani Steadfast Emblem',
     'mana_cost': '',
     'cmc': 0.0,
     'type_line': 'Emblem — Ajani',
     'oracle_text': 'If a source would deal damage to you or a '
                    'planeswalker you control, prevent all but 1 of that '
                    'damage.',
     'colors': [],
     'color_identity': [],
     'keywords': [],
     'produced_mana': [],
     'legalities': {'commander': 'not_legal'},
     'layout': 'emblem',
     'reserved': False,
     'edhrec_rank': None,
     'released_at': '2023-08-04',
     'set': 'tcmm'},
]


#: The one pool this process ever actually builds. `CARDS` is a module-level
#: constant, so every `build` call in a run produces the same database --
#: which makes the DuckDB ingest (~1.2s) worth doing once and the rest of the
#: time copying the closed file (~10ms). Held as a `TemporaryDirectory` so the
#: interpreter cleans it up on exit; each caller still gets its own private
#: copy at `db_path`, so a test that mutated its pool would corrupt nothing
#: but its own.
_CACHE_DIR: tempfile.TemporaryDirectory[str] | None = None


# ------------------------------------------------------------- printings
#
# The corner tier of `cards/identify.py` reads a set code and a collector
# number off the bottom-left of a photographed card and looks the pair up
# here, so these rows are what make it testable without the real table's
# 107,338. Same rule as `CARDS` above: **every value was read out of the
# real pool**, this time straight from `printings`, and pasted verbatim.
#
# Chosen for the cases rather than for coverage:
#
# * **Sol Ring in two sets** (`ltc` 284 -- the very line `decklist.py`'s
#   docstring uses as its example -- and `lea` 269), because one card with
#   two printings is the normal situation and both pairs must resolve to
#   the same name.
# * **Goreclaw twice in one set** (`mul` 157 and `mul` 157z): a
#   letter-suffixed collector number beside its plain sibling. Both are the
#   same card, which is why `by_printing`'s `DISTINCT name` resolves rather
#   than refusing -- a real ambiguity is two *names*, not two rows.
# * **Two double-faced cards** (`mom` 137 Etali, `mh3` 237 Ajani), whose
#   printings carry their image on the faces rather than at the top level.
# * **Two banned cards** (`m12` 188 Primeval Titan, `roe` 4 Emrakul),
#   because the reader must be able to name a card the gate will then
#   refuse -- this library's own decks run both.
# * **`lea` 232 Black Lotus and `lea` 294 Forest**, an old frame that
#   prints no collector number on the card at all. The pool holds numbers
#   for them; a camera pointed at one will not, which is the entire reason
#   the title tier exists beside this one.
PRINTINGS = [{'id': '5805f64c-dd88-4e94-8f0a-a01dae67e3ba',
  'oracle_id': '6ad8011d-3471-4369-9d68-b264cc027487',
  'name': 'Sol Ring',
  'set': 'ltc',
  'set_name': 'Tales of Middle-earth Commander',
  'collector_number': '284',
  'rarity': 'uncommon',
  'released_at': '2023-06-23',
  'digital': False,
  'promo': False,
  'finishes': ['nonfoil'],
  'artist': 'L J Koh',
  'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/5/8/5805f64c-dd88-4e94-8f0a-a01dae67e3ba.jpg?1783915895'},
  'prices': {'usd': '2.51', 'usd_foil': None, 'eur': '1.77'}},
 {'id': 'c4300d24-1cae-4dd5-be7e-38cc677cf5bd',
  'oracle_id': '6ad8011d-3471-4369-9d68-b264cc027487',
  'name': 'Sol Ring',
  'set': 'lea',
  'set_name': 'Limited Edition Alpha',
  'collector_number': '269',
  'rarity': 'uncommon',
  'released_at': '1993-08-05',
  'digital': False,
  'promo': False,
  'finishes': ['nonfoil'],
  'artist': 'Mark Tedin',
  'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/c/4/c4300d24-1cae-4dd5-be7e-38cc677cf5bd.jpg?1783948661'},
  'prices': {'usd': None, 'usd_foil': None, 'eur': '1126.22'}},
 {'id': '95c14c4d-6c16-4826-8d93-d89ad04aee09',
  'oracle_id': '7514e401-7aa1-405d-9f7a-312b4e630cc2',
  'name': 'Etali, Primal Conqueror // Etali, Primal Sickness',
  'set': 'mom',
  'set_name': 'March of the Machine',
  'collector_number': '137',
  'rarity': 'rare',
  'released_at': '2023-04-21',
  'digital': False,
  'promo': False,
  'finishes': ['nonfoil', 'foil'],
  'artist': 'Ryan Pancoast',
  'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/9/5/95c14c4d-6c16-4826-8d93-d89ad04aee09.jpg?1783916997'},
  'prices': {'usd': '32.74', 'usd_foil': '37.64', 'eur': '20.92'}},
 {'id': '0d16e8e0-31b2-4389-afd6-783c501f6fa0',
  'oracle_id': '2588f348-d7a3-46c8-9ace-dca53ed5ef99',
  'name': 'Ajani, Nacatl Pariah // Ajani, Nacatl Avenger',
  'set': 'mh3',
  'set_name': 'Modern Horizons 3',
  'collector_number': '237',
  'rarity': 'mythic',
  'released_at': '2024-06-14',
  'digital': False,
  'promo': False,
  'finishes': ['nonfoil', 'foil'],
  'artist': 'Chris Rallis',
  'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/0/d/0d16e8e0-31b2-4389-afd6-783c501f6fa0.jpg?1783911238'},
  'prices': {'usd': '10.38', 'usd_foil': '10.8', 'eur': '10.76'}},
 {'id': 'fd6ddbca-b943-49d6-b341-509bb72dd5a6',
  'oracle_id': 'ae83ef2c-960f-4c5b-97cc-52465c687c18',
  'name': 'Primeval Titan',
  'set': 'm12',
  'set_name': 'Magic 2012',
  'collector_number': '188',
  'rarity': 'mythic',
  'released_at': '2011-07-15',
  'digital': False,
  'promo': False,
  'finishes': ['nonfoil', 'foil'],
  'artist': 'Aleksi Briclot',
  'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/f/d/fd6ddbca-b943-49d6-b341-509bb72dd5a6.jpg?1783941057'},
  'prices': {'usd': '8.71', 'usd_foil': '28.54', 'eur': '4.68'}},
 {'id': '080a5356-61d9-46cf-9095-d59c048f9d77',
  'oracle_id': 'befb211f-37ca-4083-98d4-9ff1f28be3f2',
  'name': 'Goreclaw, Terror of Qal Sisma',
  'set': 'mul',
  'set_name': 'Multiverse Legends',
  'collector_number': '157',
  'rarity': 'rare',
  'released_at': '2023-04-21',
  'digital': False,
  'promo': False,
  'finishes': ['foil'],
  'artist': 'Domenico Cava',
  'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/0/8/080a5356-61d9-46cf-9095-d59c048f9d77.jpg?1783916808'},
  'prices': {'usd': None, 'usd_foil': '19.75', 'eur': None}},
 {'id': 'f4d18240-d843-4573-b490-5ee72ceb4c1e',
  'oracle_id': 'befb211f-37ca-4083-98d4-9ff1f28be3f2',
  'name': 'Goreclaw, Terror of Qal Sisma',
  'set': 'mul',
  'set_name': 'Multiverse Legends',
  'collector_number': '157z',
  'rarity': 'rare',
  'released_at': '2023-04-21',
  'digital': False,
  'promo': False,
  'finishes': ['foil'],
  'artist': 'Domenico Cava',
  'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/f/4/f4d18240-d843-4573-b490-5ee72ceb4c1e.jpg?1783916806'},
  'prices': {'usd': None, 'usd_foil': '499.95', 'eur': None}},
 {'id': '5dd7dd1a-6dd1-43c3-8298-7db703d384a1',
  'oracle_id': '0f1b5cea-2035-444c-9f63-87dcb9782c74',
  'name': 'Gyome, Master Chef',
  'set': 'c21',
  'set_name': 'Commander 2021',
  'collector_number': '5',
  'rarity': 'mythic',
  'released_at': '2021-04-23',
  'digital': False,
  'promo': False,
  'finishes': ['foil'],
  'artist': 'Steve Prescott',
  'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/5/d/5dd7dd1a-6dd1-43c3-8298-7db703d384a1.jpg?1783927614'},
  'prices': {'usd': None, 'usd_foil': '5.64', 'eur': None}},
 {'id': '67600383-bbb8-411c-b8e6-2296650bc747',
  'oracle_id': '900ca697-ad38-4b2b-bc74-2ff7eb6ea951',
  'name': 'Emrakul, the Aeons Torn',
  'set': 'roe',
  'set_name': 'Rise of the Eldrazi',
  'collector_number': '4',
  'rarity': 'mythic',
  'released_at': '2010-04-23',
  'digital': False,
  'promo': False,
  'finishes': ['nonfoil', 'foil'],
  'artist': 'Mark Tedin',
  'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/6/7/67600383-bbb8-411c-b8e6-2296650bc747.jpg?1783942013'},
  'prices': {'usd': '27.93', 'usd_foil': '194.7', 'eur': '24.0'}},
 {'id': 'c34d66f5-e782-425c-9260-e8989a9cf50b',
  'oracle_id': '8c52bd39-0586-48ca-b263-17210cf9feb6',
  'name': 'Craterhoof Behemoth',
  'set': 'mm3',
  'set_name': 'Modern Masters 2017',
  'collector_number': '122',
  'rarity': 'mythic',
  'released_at': '2017-03-17',
  'digital': False,
  'promo': False,
  'finishes': ['nonfoil', 'foil'],
  'artist': 'Chris Rahn',
  'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/c/3/c34d66f5-e782-425c-9260-e8989a9cf50b.jpg?1783936635'},
  'prices': {'usd': '24.38', 'usd_foil': '20.41', 'eur': '16.57'}},
 {'id': 'b0faa7f2-b547-42c4-a810-839da50dadfe',
  'oracle_id': '5089ec1a-f881-4d55-af14-5d996171203b',
  'name': 'Black Lotus',
  'set': 'lea',
  'set_name': 'Limited Edition Alpha',
  'collector_number': '232',
  'rarity': 'rare',
  'released_at': '1993-08-05',
  'digital': False,
  'promo': False,
  'finishes': ['nonfoil'],
  'artist': 'Christopher Rush',
  'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/b/0/b0faa7f2-b547-42c4-a810-839da50dadfe.jpg?1783948669'},
  'prices': {'usd': None, 'usd_foil': None, 'eur': '38719.86'}},
 {'id': '6f1c8cb0-38eb-408b-94e8-16db83999b3b',
  'oracle_id': 'b34bb2dc-c1af-4d77-b0b3-a0fb342a5fc6',
  'name': 'Forest',
  'set': 'lea',
  'set_name': 'Limited Edition Alpha',
  'collector_number': '294',
  'rarity': 'common',
  'released_at': '1993-08-05',
  'digital': False,
  'promo': False,
  'finishes': ['nonfoil'],
  'artist': 'Christopher Rush',
  'image_uris': {'normal': 'https://cards.scryfall.io/normal/front/6/f/6f1c8cb0-38eb-408b-94e8-16db83999b3b.jpg?1783948656'},
  'prices': {'usd': '32.25', 'usd_foil': None, 'eur': '30.83'}}]

def build(db_path: Path) -> Path:
    """Create a card pool at `db_path`. Returns it, so callers can chain.

    Built once per process and copied thereafter -- see `_CACHE_DIR`. Before
    the cache, the ~75 tests taking a `pool` fixture each paid the ingest
    themselves, which was about two of the suite's six minutes.
    """
    global _CACHE_DIR
    if _CACHE_DIR is None:
        _CACHE_DIR = tempfile.TemporaryDirectory(prefix="tiny-pool-")
        _build_into(Path(_CACHE_DIR.name) / "tiny.duckdb")
    db_path = Path(db_path)
    db_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(Path(_CACHE_DIR.name) / "tiny.duckdb", db_path)
    return db_path


def _build_into(db_path: Path) -> None:
    from mtglab.cards.db import connect, load_oracle, load_printings

    jsonl = Path(db_path).parent / "tiny-oracle.jsonl"
    jsonl.parent.mkdir(parents=True, exist_ok=True)
    jsonl.write_text("\n".join(json.dumps(c) for c in CARDS), encoding="utf-8")

    printings = Path(db_path).parent / "tiny-printings.jsonl"
    printings.write_text("\n".join(json.dumps(p) for p in PRINTINGS),
                         encoding="utf-8")

    con = connect(db_path)
    try:
        load_oracle(con, jsonl)
        load_printings(con, printings)
    finally:
        con.close()


# --------------------------------------------------------------- a real deck
#
# The API's card-fact tests used to run against `decks/goreclaw-stompy`, which
# meant they needed the whole 35,000-card pool to say anything -- and so they
# skipped everywhere except the maintainer's laptop. This deck is built
# entirely out of the cards above, so the same assertions run against a card pool
# CI can construct in about a second.
#
# It is deliberately *shaped* like Goreclaw's real list rather than being it:
# a mono-green commander, a legal 99, and exactly one banned card. What it is
# not is a plausible deck -- 92 Forests is not a mana base, it is the cheapest
# legal way to reach 99 cards without inventing ninety more fixture rows.
# Nothing here should be read as deckbuilding advice, and nothing in `decks/`
# depends on it.

#: The non-basic slots. Basics fill the rest.
#:
#: Deliberately short. `suggest.replacements_for` excludes everything already
#: in the list, so a fixture that ran every green creature in `CARDS` would
#: shortlist nothing and `assert target["candidates"]` would be asserting the
#: absence of a bug it could no longer see. Craterhoof Behemoth, Terastodon
#: and Woodfall Primus are held *out* of the deck on purpose, so they are
#: available as candidates for the Titan's slot.
_SPELLS = [
    ("Sol Ring", "ramp", "Two mana on turn one, and it always has been."),
    ("Regal Behemoth", "threat", "Doubles the mana and refills the hand."),
    ("Vorinclex, Voice of Hunger", "threat", "Taxes every opponent's mana."),
]

#: Swapped in for the banned Titan when a clean deck is what's wanted.
_LEGAL_SEVEN_DROP = (
    "Cultivator Colossus", "threat",
    "Trample body that puts lands onto the battlefield; ramp and threat in one.",
)

#: The one illegal card, so the gate has exactly one thing to say.
_BANNED = ("Primeval Titan", "threat", "Banned in Commander -- deliberately.")


def mono_green_deck(*, clean: bool = False, stage: str = "curated"):
    """A 99-card mono-green deck built only from `CARDS`.

    With `clean=False` (the default) it runs Primeval Titan and fails the gate
    on exactly that one card, which is what makes "the gate found something"
    and "a suggestion was offered" testable. With `clean=True` the Titan's slot
    is a legal seven-drop instead and the deck passes, which is what makes
    "a clean deck has nothing to suggest" testable without a second fixture.

    Returned fresh each call: `MemoryDeckSource` mutates what it is given, and
    a shared instance would leak one test's edits into the next.
    """
    from mtglab.decks.model import CardEntry, Deck

    spells = [*_SPELLS, _LEGAL_SEVEN_DROP if clean else _BANNED]
    cards = [CardEntry(name=n, category=c, why=w) for n, c, w in spells]
    cards.append(CardEntry(
        name="Forest", category="land", qty=99 - len(spells),
        why="Basic, untapped, and the only green source this list needs."))
    assert sum(c.qty for c in cards) == 99, "the fixture deck is not 99 cards"

    return Deck(
        slug="mono-green",
        name="Mono-Green Fixture",
        status="theoretical",
        stage=stage,
        commander=["Goreclaw, Terror of Qal Sisma"],
        bracket=2,
        strategy="A fixture, not a deck. See tests/tiny_pool.py.",
        cards=cards,
    )


# A 99 built from the cards above: one Sol Ring, one banned Titan, and basics
# for the rest. Basics are exempt from the singleton rule, so this is a legally
# sized decklist that fails the gate on exactly one thing.
DECKLIST = """\
Commander
1 Gyome, Master Chef

Deck
1 Sol Ring
1 Primeval Titan
97 Swamp
"""
